name: Deploy

on:
  push:
    # branches: [ dev ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
          sudo apt update
          sudo apt upgrade -y
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install php8.1 php8.1-mysql -y
          sudo apt-get install php8.1-xml php8.1-curl -y
          sudo apt-get install zip unzip -y
          git clone https://github.com/laravel/laravel.git
          ls
          cd laravel
          ls
          pwd
          sudo apt install composer
          sudo service apache2 restart
          composer install
              '
